version: '3.3'

#volumes:
#  portal-db-data:

services:
  carbon-db:
    image: mariadb:10.7.1
    container_name: carbon-db
    # restart: always
    environment:
      MARIADB_ROOT_PASSWORD: sbmroot
      MARIADB_DATABASE: carbon
    ports:
      - "3306:3306"
    # networks:
      # - portal-net
    volumes:
      - "./sql/2.x/:/docker-entrypoint-initdb.d/"
      - "./sql/2.x/FUNCTIONS/:/FUNCTIONS/"
      - "./sql/2.x/PROCS/:/PROCS/"
      #- "portal-db-data:/var/lib/mysql"
    healthcheck:
      test: "mysqladmin -psbmroot ping -h localhost"
      interval: 30s
      timeout: 20s
      retries: 3